name: Node.js CI
on:
  push:
    branches: [ "main" ]
  # Actions run on Pull Requests are used to run test suites
  # to ensure no broken code is merged to main!
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-node@v3
      with:
        cache: 'npm'

    - name: Change to the front directory
      run: cd front-film-categories

    - name: Build React app
      run: npm run build
    
    - name: Sync s3 bucket
      run: npm run deploy
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }} 
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_DEFAULT_REGION: "us-west-2"
